### ISSUE TITLE
Refactor write_model.jl

### ISSUE THREAD

**Issue by daniel-thom** [NREL/PowerSimulations.jl#215]
Suggest some refactoring in this file to make the functionality easier to read and reuse.

- [x] _write_variable_results() writes a dictionary of dataframes to files.  This could be made more generic. write_data could be a good name.  Different methods could dispatch to different implementations. One method could implement this logic. Another method could take a DataFrame and write that to a single file.  Secondly, we could consider supporting different file types.  This could be either a method parameter or just detecting the file type.  All of this functionality could go into InfrastructureSystems.
- [ ]  _write_optimizer_log() writes 3 integers and a timestamp to a DataFrame.  Is a JSON file more appropriate?  I suggest creating a struct with these fields and then serialize/deserialize with JSON.
- [x] _write_time_stamps() accepts a dataframe, creates a new dataframe from that, and then writes that to a feather file. The second dataframe doesn't appear necessary.  If InfrastructureSystems has a write_data(df::DataFrame, filename) method then this call site can call that instead. This function can be removed.
- [x] If MOI.get(canonical_model.JuMPmodel, MOI.SolveTime()) throws an exception in _export_optimizer_log() then the code writes an error message as a string to a variable that would otherwise get what seems like a timestamp or duration. This mixes types and adds complexity during parsing. A status field might be better.

**Comment by jd-lara** [comment]
@Lilyhanig please take a look at this since you have been working on the code to write/read models and results.

**Comment by jd-lara** [comment]
@daniel-thom  about this comment " If MOI.get(canonical_model.JuMPmodel, MOI.SolveTime()) throws an exception in _export_optimizer_log() then the code writes an error message as a string to a variable that would otherwise get what seems like a timestamp or duration. This mixes types and adds complexity during parsing. A status field might be better." 

This is because some solvers don't support the solution times and others do. The ones that do return a float and the ones that don't they don't return anything. What do you suggest we do in those cases? I find it more informative to have the return error in the field when isn't available.

**Comment by daniel-thom** [comment]
The problem is that a developer (not a user) interpreting the results has to discern a time-formatted string vs an error string.  I think an empty string is better.  And the existing warning log message.  You could also have a solver_time_valid field, but that's probably unnecessary.

**Comment by jd-lara** [comment]
I have added this problem to #229 so we can tackle that directly in logging.
