### ISSUE TITLE
Check the formulation of the flow_limits in the lines. 

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSimulations.jl#78]
There are weird lines in the code of `flow_constraints.jl` that need review.

**Comment by claytonpbarrows** [comment]
Initial scaling tests reveal that the default enforcement of all transmission flow limits expands memory usage and limits model size. We should make the enforcement of transmission limits more easily configurable. Essentially, I think we need two options:
 - Easy filters for enforcing transmission flow limits (e.g. baseKV > XXX)
 - Dynamic (column generation) enforcement.

**Comment by ccoffrin** [comment]
I am open to adding optional line limits to PowerModels, but first I would like to better understand the conditions that result in these high-memory models.  

Note that, my preliminary experiment in https://github.com/lanl-ansi/PowerModels.jl/issues/422 suggested that explicit line flow variables did not create a significant slowdown.  In that case, active power only flow limits should be cheap, as they are implemented as variable bounds.

**Comment by jd-lara** [comment]
I agree with @ccoffrin. There is no reason to think variable bounds can lead to scalability issues. If we can get more information about these tests it will be very useful

**Comment by claytonpbarrows** [comment]
Fair enough. I suppose the title of this issue is more fitting than I had originally assumed. Currently, flow limits are created with constraints. So, my comments are W.R.T the population of the constraints that we have currently formulated.  I agree that we should check the formulation and see if the scaling problems are addressed by adding flow limits as variable bounds instead of constraints.
Thanks @ccoffrin
